### ISSUE TITLE
  cert_chain must not be nil

### ISSUE THREAD

**Issue by Zhengquan** [derdewey/tlsmail#2]
## issue

Gemfile:

```
gem 'tlsmail', :git => 'git://github.com/derdewey/tlsmail.git'
```

When execute `bundle install`,it has the following warning.

tlsmail at /home/kit/.rvm/gems/ruby-1.9.2-p290/bundler/gems/tlsmail-8b17b3b0ff22 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  **cert_chain must not be nil**

Bundler version 1.0.21

**Comment by rdeguzman** [comment]
in tlsmail.gemspec or see https://github.com/rdeguzman/tlsmail/blob/master/tlsmail.gemspec

```
s.cert_chain = []
```

**Comment by Zhengquan** [comment]
@rdeguzman Thanks,solve my problem!
